export const LANGUAGES = {
    aa: {
        name: {
            tr: "Afar",
            en: "Afar",
            fr: "afar",
            de: "Afar",
            es: "afar",
        },
        nativeName: "Afaraf",
        iso2: "AA",
        iso3: "AAR",
        direction: "ltr",
    },
    ab: {
        name: {
            tr: "Abhazca",
            en: "Abkhazian",
            fr: "abkhaze",
            de: "Abchasisch",
            es: "abjasio",
        },
        nativeName: "Аҧсуа",
        iso2: "AB",
        iso3: "ABK",
        direction: "ltr",
    },
    ae: {
        name: {
            tr: "Avestçe",
            en: "Avestan",
            fr: "avestique",
            de: "Avestisch",
            es: "avéstico",
        },
        nativeName: "Avesta",
        iso2: "AE",
        iso3: "AVE",
        direction: "ltr",
    },
    af: {
        name: {
            tr: "Afrikaanca",
            en: "Afrikaans",
            fr: "afrikaans",
            de: "Afrikaans",
            es: "afrikáans",
        },
        nativeName: "Afrikaans",
        iso2: "AF",
        iso3: "AFR",
        direction: "ltr",
    },
    ak: {
        name: {
            tr: "Akan",
            en: "Akan",
            fr: "akan",
            de: "Akan",
            es: "akan",
        },
        nativeName: "Akan",
        iso2: "AK",
        iso3: "AKA",
        direction: "ltr",
    },
    am: {
        name: {
            tr: "Amharca",
            en: "Amharic",
            fr: "amharique",
            de: "Amharisch",
            es: "amárico",
        },
        nativeName: "አማርኛ",
        iso2: "AM",
        iso3: "AMH",
        direction: "ltr",
    },
    an: {
        name: {
            tr: "Aragonca",
            en: "Aragonese",
            fr: "aragonais",
            de: "Aragonesisch",
            es: "aragonés",
        },
        nativeName: "Aragonés",
        iso2: "AN",
        iso3: "ARG",
        direction: "ltr",
    },
    ar: {
        name: {
            tr: "Arapça",
            en: "Arabic",
            fr: "Arabe",
            de: "Arabisch",
            es: "Árabe",
        },
        nativeName: "العربية",
        iso2: "AR",
        iso3: "ARA",
        direction: "rtl",
    },
    as: {
        name: {
            tr: "Assamca",
            en: "Assamese",
            fr: "assamais",
            de: "Assamesisch",
            es: "asamés",
        },
        nativeName: "অসমীয়া",
        iso2: "AS",
        iso3: "ASM",
        direction: "ltr",
    },
    av: {
        name: {
            tr: "Avar dili",
            en: "Avaric",
            fr: "avar",
            de: "Awarisch",
            es: "avar",
        },
        nativeName: "Авар мацӀ",
        iso2: "AV",
        iso3: "AVA",
        direction: "ltr",
    },
    ay: {
        name: {
            tr: "Aymara",
            en: "Aymara",
            fr: "aymara",
            de: "Aymara",
            es: "aimara",
        },
        nativeName: "Aymar aru",
        iso2: "AY",
        iso3: "AYM",
        direction: "ltr",
    },
    az: {
        name: {
            tr: "Azerbaycan Türkçesi",
            en: "Azerbaijani",
            fr: "Azéri",
            de: "Aserbaidschanisch",
            es: "Azerbaiyano",
        },
        nativeName: "Azərbaycanca",
        iso2: "AZ",
        iso3: "AZE",
        direction: "ltr",
    },
    ba: {
        name: {
            tr: "Başkırtça",
            en: "Bashkir",
            fr: "bachkir",
            de: "Baschkirisch",
            es: "baskir",
        },
        nativeName: "Башҡортса",
        iso2: "BA",
        iso3: "BAK",
        direction: "ltr",
    },
    be: {
        name: {
            tr: "Belarusça",
            en: "Belarusian",
            fr: "Biélorusse",
            de: "Belarussisch",
            es: "Bielorruso",
        },
        nativeName: "Беларуская",
        iso2: "BE",
        iso3: "BEL",
        direction: "ltr",
    },
    bg: {
        name: {
            tr: "Bulgarca",
            en: "Bulgarian",
            fr: "Bulgare",
            de: "Bulgarisch",
            es: "Búlgaro",
        },
        nativeName: "Български",
        iso2: "BG",
        iso3: "BUL",
        direction: "ltr",
    },
    bi: {
        name: {
            tr: "Bislama",
            en: "Bislama",
            fr: "bichelamar",
            de: "Bislama",
            es: "bislama",
        },
        nativeName: "Bislama",
        iso2: "BI",
        iso3: "BIS",
        direction: "ltr",
    },
    bm: {
        name: {
            tr: "Bambara",
            en: "Bambara",
            fr: "bambara",
            de: "Bambara",
            es: "bambara",
        },
        nativeName: "Bamanankan",
        iso2: "BM",
        iso3: "BAM",
        direction: "ltr",
    },
    bn: {
        name: {
            tr: "Bengalce",
            en: "Bangla",
            fr: "bengali",
            de: "Bengalisch",
            es: "bengalí",
        },
        nativeName: "বাংলা",
        iso2: "BN",
        iso3: "BEN",
        direction: "ltr",
    },
    bo: {
        name: {
            tr: "Tibetçe",
            en: "Tibetan",
            fr: "tibétain",
            de: "Tibetisch",
            es: "tibetano",
        },
        nativeName: "བོད་ཡིག",
        iso2: "BO",
        iso3: "TIB",
        direction: "ltr",
    },
    br: {
        name: {
            tr: "Bretonca",
            en: "Breton",
            fr: "breton",
            de: "Bretonisch",
            es: "bretón",
        },
        nativeName: "Brezhoneg",
        iso2: "BR",
        iso3: "BRE",
        direction: "ltr",
    },
    bs: {
        name: {
            tr: "Boşnakça",
            en: "Bosnian",
            fr: "Bosniaque",
            de: "Bosnisch",
            es: "Bosnio",
        },
        nativeName: "Bosanski",
        iso2: "BS",
        iso3: "BOS",
        direction: "ltr",
    },
    ca: {
        name: {
            tr: "Katalanca",
            en: "Catalan",
            fr: "catalan",
            de: "Katalanisch",
            es: "catalán",
        },
        nativeName: "Català",
        iso2: "CA",
        iso3: "CAT",
        direction: "ltr",
    },
    ce: {
        name: {
            tr: "Çeçence",
            en: "Chechen",
            fr: "tchétchène",
            de: "Tschetschenisch",
            es: "checheno",
        },
        nativeName: "Нохчийн мотт",
        iso2: "CE",
        iso3: "CHE",
        direction: "ltr",
    },
    ch: {
        name: {
            tr: "Çamorro dili",
            en: "Chamorro",
            fr: "chamorro",
            de: "Chamorro",
            es: "chamorro",
        },
        nativeName: "Chamoru",
        iso2: "CH",
        iso3: "CHA",
        direction: "ltr",
    },
    co: {
        name: {
            tr: "Korsikaca",
            en: "Corsican",
            fr: "corse",
            de: "Korsisch",
            es: "corso",
        },
        nativeName: "Corsu",
        iso2: "CO",
        iso3: "COS",
        direction: "ltr",
    },
    cr: {
        name: {
            tr: "Krice",
            en: "Cree",
            fr: "cree",
            de: "Cree",
            es: "cree",
        },
        nativeName: "ᓀᐦᐃᔭᐍᐏᐣ",
        iso2: "CR",
        iso3: "CRE",
        direction: "ltr",
    },
    cs: {
        name: {
            tr: "Çekçe",
            en: "Czech",
            fr: "Tchèque",
            de: "Tschechisch",
            es: "Checo",
        },
        nativeName: "Čeština",
        iso2: "CS",
        iso3: "CZE",
        direction: "ltr",
    },
    cu: {
        name: {
            tr: "Kilise Slavcası",
            en: "Church Slavic",
            fr: "slavon d’église",
            de: "Kirchenslawisch",
            es: "eslavo eclesiástico",
        },
        nativeName: "Словѣньскъ",
        iso2: "CU",
        iso3: "CHU",
        direction: "ltr",
    },
    cv: {
        name: {
            tr: "Çuvaşça",
            en: "Chuvash",
            fr: "tchouvache",
            de: "Tschuwaschisch",
            es: "chuvasio",
        },
        nativeName: "Чӑвашла",
        iso2: "CV",
        iso3: "CHV",
        direction: "ltr",
    },
    cy: {
        name: {
            tr: "Galce",
            en: "Welsh",
            fr: "gallois",
            de: "Walisisch",
            es: "galés",
        },
        nativeName: "Cymraeg",
        iso2: "CY",
        iso3: "WEL",
        direction: "ltr",
    },
    da: {
        name: {
            tr: "Danca",
            en: "Danish",
            fr: "Danois",
            de: "Dänisch",
            es: "Danés",
        },
        nativeName: "Dansk",
        iso2: "DA",
        iso3: "DAN",
        direction: "ltr",
    },
    de: {
        name: {
            tr: "Almanca",
            en: "German",
            fr: "Allemand",
            de: "Deutsch",
            es: "Alemán",
        },
        nativeName: "Deutsch",
        iso2: "DE",
        iso3: "GER",
        direction: "ltr",
    },
    dv: {
        name: {
            tr: "Divehi dili",
            en: "Divehi",
            fr: "maldivien",
            de: "Dhivehi",
            es: "divehi",
        },
        nativeName: "ދިވެހި",
        iso2: "DV",
        iso3: "DIV",
        direction: "rtl",
    },
    dz: {
        name: {
            tr: "Dzongkha",
            en: "Dzongkha",
            fr: "dzongkha",
            de: "Dzongkha",
            es: "dzongkha",
        },
        nativeName: "རྫོང་ཁ",
        iso2: "DZ",
        iso3: "DZO",
        direction: "ltr",
    },
    ee: {
        name: {
            tr: "Ewe",
            en: "Ewe",
            fr: "éwé",
            de: "Ewe",
            es: "ewé",
        },
        nativeName: "Eʋegbe",
        iso2: "EE",
        iso3: "EWE",
        direction: "ltr",
    },
    el: {
        name: {
            tr: "Yunanca",
            en: "Greek",
            fr: "Grec",
            de: "Griechisch",
            es: "Griego",
        },
        nativeName: "Ελληνικά",
        iso2: "EL",
        iso3: "GRE",
        direction: "ltr",
    },
    en: {
        name: {
            tr: "İngilizce",
            en: "English",
            fr: "Anglais",
            de: "Englisch",
            es: "Inglés",
        },
        nativeName: "English",
        iso2: "EN",
        iso3: "ENG",
        direction: "ltr",
    },
    eo: {
        name: {
            tr: "Esperanto",
            en: "Esperanto",
            fr: "espéranto",
            de: "Esperanto",
            es: "esperanto",
        },
        nativeName: "Esperanto",
        iso2: "EO",
        iso3: "EPO",
        direction: "ltr",
    },
    es: {
        name: {
            tr: "İspanyolca",
            en: "Spanish",
            fr: "Espagnol",
            de: "Spanisch",
            es: "Español",
        },
        nativeName: "Español",
        iso2: "ES",
        iso3: "SPA",
        direction: "ltr",
    },
    et: {
        name: {
            tr: "Estonca",
            en: "Estonian",
            fr: "estonien",
            de: "Estnisch",
            es: "estonio",
        },
        nativeName: "Eesti",
        iso2: "ET",
        iso3: "EST",
        direction: "ltr",
    },
    eu: {
        name: {
            tr: "Baskça",
            en: "Basque",
            fr: "basque",
            de: "Baskisch",
            es: "euskera",
        },
        nativeName: "Euskara",
        iso2: "EU",
        iso3: "BAQ",
        direction: "ltr",
    },
    fa: {
        name: {
            tr: "Farsça",
            en: "Persian",
            fr: "Persan",
            de: "Persisch",
            es: "Persa",
        },
        nativeName: "فارسی",
        iso2: "FA",
        iso3: "PER",
        direction: "rtl",
    },
    ff: {
        name: {
            tr: "Fula dili",
            en: "Fula",
            fr: "peul",
            de: "Ful",
            es: "fula",
        },
        nativeName: "Fulfulde",
        iso2: "FF",
        iso3: "FUL",
        direction: "ltr",
    },
    fi: {
        name: {
            tr: "Fince",
            en: "Finnish",
            fr: "Finnois",
            de: "Finnisch",
            es: "Finés",
        },
        nativeName: "Suomi",
        iso2: "FI",
        iso3: "FIN",
        direction: "ltr",
    },
    fj: {
        name: {
            tr: "Fiji dili",
            en: "Fijian",
            fr: "fidjien",
            de: "Fidschi",
            es: "fiyiano",
        },
        nativeName: "Vosa Vakaviti",
        iso2: "FJ",
        iso3: "FIJ",
        direction: "ltr",
    },
    fo: {
        name: {
            tr: "Faroe dili",
            en: "Faroese",
            fr: "féroïen",
            de: "Färöisch",
            es: "feroés",
        },
        nativeName: "Føroyskt",
        iso2: "FO",
        iso3: "FAO",
        direction: "ltr",
    },
    fr: {
        name: {
            tr: "Fransızca",
            en: "French",
            fr: "Français",
            de: "Französisch",
            es: "Francés",
        },
        nativeName: "Français",
        iso2: "FR",
        iso3: "FRE",
        direction: "ltr",
    },
    fy: {
        name: {
            tr: "Batı Frizcesi",
            en: "Western Frisian",
            fr: "frison occidental",
            de: "Westfriesisch",
            es: "frisón occidental",
        },
        nativeName: "Frysk",
        iso2: "FY",
        iso3: "FRY",
        direction: "ltr",
    },
    ga: {
        name: {
            tr: "İrlandaca",
            en: "Irish",
            fr: "irlandais",
            de: "Irisch",
            es: "irlandés",
        },
        nativeName: "Gaeilge",
        iso2: "GA",
        iso3: "GLE",
        direction: "ltr",
    },
    gd: {
        name: {
            tr: "İskoç Gaelcesi",
            en: "Scottish Gaelic",
            fr: "gaélique écossais",
            de: "Gälisch",
            es: "gaélico escocés",
        },
        nativeName: "Gàidhlig",
        iso2: "GD",
        iso3: "GLA",
        direction: "ltr",
    },
    gl: {
        name: {
            tr: "Galiçyaca",
            en: "Galician",
            fr: "galicien",
            de: "Galicisch",
            es: "gallego",
        },
        nativeName: "Galego",
        iso2: "GL",
        iso3: "GLG",
        direction: "ltr",
    },
    gn: {
        name: {
            tr: "Guarani dili",
            en: "Guarani",
            fr: "guarani",
            de: "Guaraní",
            es: "guaraní",
        },
        nativeName: "Avañe'ẽ",
        iso2: "GN",
        iso3: "GRN",
        direction: "ltr",
    },
    gu: {
        name: {
            tr: "Güceratça",
            en: "Gujarati",
            fr: "goudjarati",
            de: "Gujarati",
            es: "guyaratí",
        },
        nativeName: "ગુજરાતી",
        iso2: "GU",
        iso3: "GUJ",
        direction: "ltr",
    },
    gv: {
        name: {
            tr: "Man dili",
            en: "Manx",
            fr: "mannois",
            de: "Manx",
            es: "manés",
        },
        nativeName: "Gaelg",
        iso2: "GV",
        iso3: "GLV",
        direction: "ltr",
    },
    ha: {
        name: {
            tr: "Hausa dili",
            en: "Hausa",
            fr: "haoussa",
            de: "Haussa",
            es: "hausa",
        },
        nativeName: "Hausa",
        iso2: "HA",
        iso3: "HAU",
        direction: "ltr",
    },
    he: {
        name: {
            tr: "İbranice",
            en: "Hebrew",
            fr: "Hébreu",
            de: "Hebräisch",
            es: "Hebreo",
        },
        nativeName: "עברית",
        iso2: "HE",
        iso3: "HEB",
        direction: "rtl",
    },
    hi: {
        name: {
            tr: "Hintçe",
            en: "Hindi",
            fr: "Hindi",
            de: "Hindi",
            es: "Hindi",
        },
        nativeName: "हिन्दी",
        iso2: "HI",
        iso3: "HIN",
        direction: "ltr",
    },
    ho: {
        name: {
            tr: "Hiri Motu",
            en: "Hiri Motu",
            fr: "hiri motu",
            de: "Hiri-Motu",
            es: "hiri motu",
        },
        nativeName: "Hiri Motu",
        iso2: "HO",
        iso3: "HMO",
        direction: "ltr",
    },
    hr: {
        name: {
            tr: "Hırvatça",
            en: "Croatian",
            fr: "Croate",
            de: "Kroatisch",
            es: "Croata",
        },
        nativeName: "Hrvatski",
        iso2: "HR",
        iso3: "HRV",
        direction: "ltr",
    },
    ht: {
        name: {
            tr: "Haiti Kreyolu",
            en: "Haitian Creole",
            fr: "créole haïtien",
            de: "Haiti-Kreolisch",
            es: "criollo haitiano",
        },
        nativeName: "Kreyòl ayisyen",
        iso2: "HT",
        iso3: "HAT",
        direction: "ltr",
    },
    hu: {
        name: {
            tr: "Macarca",
            en: "Hungarian",
            fr: "Hongrois",
            de: "Ungarisch",
            es: "Húngaro",
        },
        nativeName: "Magyar",
        iso2: "HU",
        iso3: "HUN",
        direction: "ltr",
    },
    hy: {
        name: {
            tr: "Ermenice",
            en: "Armenian",
            fr: "Arménien",
            de: "Armenisch",
            es: "Armenio",
        },
        nativeName: "Հայերեն",
        iso2: "HY",
        iso3: "ARM",
        direction: "ltr",
    },
    hz: {
        name: {
            tr: "Herero dili",
            en: "Herero",
            fr: "héréro",
            de: "Herero",
            es: "herero",
        },
        nativeName: "Otjiherero",
        iso2: "HZ",
        iso3: "HER",
        direction: "ltr",
    },
    ia: {
        name: {
            tr: "İnterlingua",
            en: "Interlingua",
            fr: "interlingua",
            de: "Interlingua",
            es: "interlingua",
        },
        nativeName: "Interlingua",
        iso2: "IA",
        iso3: "INA",
        direction: "ltr",
    },
    id: {
        name: {
            tr: "Endonezce",
            en: "Indonesian",
            fr: "indonésien",
            de: "Indonesisch",
            es: "indonesio",
        },
        nativeName: "Bahasa Indonesia",
        iso2: "ID",
        iso3: "IND",
        direction: "ltr",
    },
    ie: {
        name: {
            tr: "Interlingue",
            en: "Interlingue",
            fr: "interlingue",
            de: "Interlingue",
            es: "interlingue",
        },
        nativeName: "Interlingue",
        iso2: "IE",
        iso3: "ILE",
        direction: "ltr",
    },
    ig: {
        name: {
            tr: "İbo dili",
            en: "Igbo",
            fr: "igbo",
            de: "Igbo",
            es: "igbo",
        },
        nativeName: "Igbo",
        iso2: "IG",
        iso3: "IBO",
        direction: "ltr",
    },
    ii: {
        name: {
            tr: "Sichuan Yi",
            en: "Sichuan Yi",
            fr: "yi du Sichuan",
            de: "Yi",
            es: "yi de Sichuán",
        },
        nativeName: "ꆈꌠ꒿",
        iso2: "II",
        iso3: "III",
        direction: "ltr",
    },
    ik: {
        name: {
            tr: "İnyupikçe",
            en: "Inupiaq",
            fr: "inupiaq",
            de: "Inupiak",
            es: "inupiaq",
        },
        nativeName: "Iñupiaq",
        iso2: "IK",
        iso3: "IPK",
        direction: "ltr",
    },
    io: {
        name: {
            tr: "Ido",
            en: "Ido",
            fr: "ido",
            de: "Ido",
            es: "ido",
        },
        nativeName: "Ido",
        iso2: "IO",
        iso3: "IDO",
        direction: "ltr",
    },
    is: {
        name: {
            tr: "İzlandaca",
            en: "Icelandic",
            fr: "islandais",
            de: "Isländisch",
            es: "islandés",
        },
        nativeName: "Íslenska",
        iso2: "IS",
        iso3: "ICE",
        direction: "ltr",
    },
    it: {
        name: {
            tr: "İtalyanca",
            en: "Italian",
            fr: "Italien",
            de: "Italienisch",
            es: "Italiano",
        },
        nativeName: "Italiano",
        iso2: "IT",
        iso3: "ITA",
        direction: "ltr",
    },
    iu: {
        name: {
            tr: "İnuktitut dili",
            en: "Inuktitut",
            fr: "inuktitut",
            de: "Inuktitut",
            es: "inuktitut",
        },
        nativeName: "ᐃᓄᒃᑎᑐᑦ",
        iso2: "IU",
        iso3: "IKU",
        direction: "ltr",
    },
    ja: {
        name: {
            tr: "Japonca",
            en: "Japanese",
            fr: "Japonais",
            de: "Japanisch",
            es: "Japonés",
        },
        nativeName: "日本語",
        iso2: "JA",
        iso3: "JPN",
        direction: "ltr",
    },
    jv: {
        name: {
            tr: "Cava dili",
            en: "Javanese",
            fr: "javanais",
            de: "Javanisch",
            es: "javanés",
        },
        nativeName: "Basa Jawa",
        iso2: "JV",
        iso3: "JAV",
        direction: "ltr",
    },
    ka: {
        name: {
            tr: "Gürcüce",
            en: "Georgian",
            fr: "Géorgien",
            de: "Georgisch",
            es: "Georgiano",
        },
        nativeName: "ქართული",
        iso2: "KA",
        iso3: "GEO",
        direction: "ltr",
    },
    kg: {
        name: {
            tr: "Kongo dili",
            en: "Kongo",
            fr: "kikongo",
            de: "Kongolesisch",
            es: "kongo",
        },
        nativeName: "Kikongo",
        iso2: "KG",
        iso3: "KON",
        direction: "ltr",
    },
    ki: {
        name: {
            tr: "Kikuyu",
            en: "Kikuyu",
            fr: "kikuyu",
            de: "Kikuyu",
            es: "kikuyu",
        },
        nativeName: "Gĩkũyũ",
        iso2: "KI",
        iso3: "KIK",
        direction: "ltr",
    },
    kj: {
        name: {
            tr: "Kuanyama",
            en: "Kuanyama",
            fr: "kuanyama",
            de: "Kwanyama",
            es: "kuanyama",
        },
        nativeName: "Kuanyama",
        iso2: "KJ",
        iso3: "KUA",
        direction: "ltr",
    },
    kk: {
        name: {
            tr: "Kazakça",
            en: "Kazakh",
            fr: "kazakh",
            de: "Kasachisch",
            es: "kazajo",
        },
        nativeName: "Қазақ тілі",
        iso2: "KK",
        iso3: "KAZ",
        direction: "ltr",
    },
    kl: {
        name: {
            tr: "Grönland dili",
            en: "Kalaallisut",
            fr: "groenlandais",
            de: "Grönländisch",
            es: "groenlandés",
        },
        nativeName: "Kalaallisut",
        iso2: "KL",
        iso3: "KAL",
        direction: "ltr",
    },
    km: {
        name: {
            tr: "Khmer dili",
            en: "Khmer",
            fr: "khmer",
            de: "Khmer",
            es: "jemer",
        },
        nativeName: "ខ្មែរ",
        iso2: "KM",
        iso3: "KHM",
        direction: "ltr",
    },
    kn: {
        name: {
            tr: "Kannada dili",
            en: "Kannada",
            fr: "kannada",
            de: "Kannada",
            es: "canarés",
        },
        nativeName: "ಕನ್ನಡ",
        iso2: "KN",
        iso3: "KAN",
        direction: "ltr",
    },
    ko: {
        name: {
            tr: "Korece",
            en: "Korean",
            fr: "Coréen",
            de: "Koreanisch",
            es: "Coreano",
        },
        nativeName: "한국어",
        iso2: "KO",
        iso3: "KOR",
        direction: "ltr",
    },
    kr: {
        name: {
            tr: "Kanuri dili",
            en: "Kanuri",
            fr: "kanouri",
            de: "Kanuri",
            es: "kanuri",
        },
        nativeName: "Kanuri",
        iso2: "KR",
        iso3: "KAU",
        direction: "ltr",
    },
    ks: {
        name: {
            tr: "Keşmir dili",
            en: "Kashmiri",
            fr: "cachemiri",
            de: "Kaschmiri",
            es: "cachemir",
        },
        nativeName: "कॉशुर",
        iso2: "KS",
        iso3: "KAS",
        direction: "ltr",
    },
    ku: {
        name: {
            tr: "Kürtçe",
            en: "Kurdish",
            fr: "kurde",
            de: "Kurdisch",
            es: "kurdo",
        },
        nativeName: "Kurdî",
        iso2: "KU",
        iso3: "KUR",
        direction: "ltr",
    },
    kv: {
        name: {
            tr: "Komi",
            en: "Komi",
            fr: "komi",
            de: "Komi",
            es: "komi",
        },
        nativeName: "Коми кыв",
        iso2: "KV",
        iso3: "KOM",
        direction: "ltr",
    },
    kw: {
        name: {
            tr: "Kernevekçe",
            en: "Cornish",
            fr: "cornique",
            de: "Kornisch",
            es: "córnico",
        },
        nativeName: "Kernewek",
        iso2: "KW",
        iso3: "COR",
        direction: "ltr",
    },
    ky: {
        name: {
            tr: "Kırgızca",
            en: "Kyrgyz",
            fr: "kirghize",
            de: "Kirgisisch",
            es: "kirguís",
        },
        nativeName: "Кыргызча",
        iso2: "KY",
        iso3: "KIR",
        direction: "ltr",
    },
    la: {
        name: {
            tr: "Latince",
            en: "Latin",
            fr: "latin",
            de: "Latein",
            es: "latín",
        },
        nativeName: "Latina",
        iso2: "LA",
        iso3: "LAT",
        direction: "ltr",
    },
    lb: {
        name: {
            tr: "Lüksemburgca",
            en: "Luxembourgish",
            fr: "luxembourgeois",
            de: "Luxemburgisch",
            es: "luxemburgués",
        },
        nativeName: "Lëtzebuergesch",
        iso2: "LB",
        iso3: "LTZ",
        direction: "ltr",
    },
    lg: {
        name: {
            tr: "Ganda",
            en: "Ganda",
            fr: "ganda",
            de: "Ganda",
            es: "ganda",
        },
        nativeName: "Luganda",
        iso2: "LG",
        iso3: "LUG",
        direction: "ltr",
    },
    li: {
        name: {
            tr: "Limburgca",
            en: "Limburgish",
            fr: "limbourgeois",
            de: "Limburgisch",
            es: "limburgués",
        },
        nativeName: "Limburgs",
        iso2: "LI",
        iso3: "LIM",
        direction: "ltr",
    },
    ln: {
        name: {
            tr: "Lingala",
            en: "Lingala",
            fr: "lingala",
            de: "Lingala",
            es: "lingala",
        },
        nativeName: "Lingála",
        iso2: "LN",
        iso3: "LIN",
        direction: "ltr",
    },
    lo: {
        name: {
            tr: "Lao dili",
            en: "Lao",
            fr: "lao",
            de: "Laotisch",
            es: "lao",
        },
        nativeName: "ລາວ",
        iso2: "LO",
        iso3: "LAO",
        direction: "ltr",
    },
    lt: {
        name: {
            tr: "Litvanca",
            en: "Lithuanian",
            fr: "lituanien",
            de: "Litauisch",
            es: "lituano",
        },
        nativeName: "Lietuvių",
        iso2: "LT",
        iso3: "LIT",
        direction: "ltr",
    },
    lu: {
        name: {
            tr: "Luba-Katanga",
            en: "Luba-Katanga",
            fr: "luba-katanga",
            de: "Luba-Katanga",
            es: "luba-katanga",
        },
        nativeName: "Tshiluba",
        iso2: "LU",
        iso3: "LUB",
        direction: "ltr",
    },
    lv: {
        name: {
            tr: "Letonca",
            en: "Latvian",
            fr: "letton",
            de: "Lettisch",
            es: "letón",
        },
        nativeName: "Latviešu",
        iso2: "LV",
        iso3: "LAV",
        direction: "ltr",
    },
    mg: {
        name: {
            tr: "Malgaşça",
            en: "Malagasy",
            fr: "malgache",
            de: "Malagasy",
            es: "malgache",
        },
        nativeName: "Malagasy",
        iso2: "MG",
        iso3: "MLG",
        direction: "ltr",
    },
    mh: {
        name: {
            tr: "Marshall Adaları dili",
            en: "Marshallese",
            fr: "marshallais",
            de: "Marschallesisch",
            es: "marshalés",
        },
        nativeName: "Kajin M̧ajeļ",
        iso2: "MH",
        iso3: "MAH",
        direction: "ltr",
    },
    mi: {
        name: {
            tr: "Maori dili",
            en: "Māori",
            fr: "maori",
            de: "Māori",
            es: "maorí",
        },
        nativeName: "Māori",
        iso2: "MI",
        iso3: "MAO",
        direction: "ltr",
    },
    mk: {
        name: {
            tr: "Makedonca",
            en: "Macedonian",
            fr: "Macédonien",
            de: "Mazedonisch",
            es: "Macedonio",
        },
        nativeName: "Македонски",
        iso2: "MK",
        iso3: "MAC",
        direction: "ltr",
    },
    ml: {
        name: {
            tr: "Malayalam dili",
            en: "Malayalam",
            fr: "malayalam",
            de: "Malayalam",
            es: "malayálam",
        },
        nativeName: "മലയാളം",
        iso2: "ML",
        iso3: "MAL",
        direction: "ltr",
    },
    mn: {
        name: {
            tr: "Moğolca",
            en: "Mongolian",
            fr: "mongol",
            de: "Mongolisch",
            es: "mongol",
        },
        nativeName: "Монгол",
        iso2: "MN",
        iso3: "MON",
        direction: "ltr",
    },
    mr: {
        name: {
            tr: "Marathi dili",
            en: "Marathi",
            fr: "marathi",
            de: "Marathi",
            es: "maratí",
        },
        nativeName: "मराठी",
        iso2: "MR",
        iso3: "MAR",
        direction: "ltr",
    },
    ms: {
        name: {
            tr: "Malayca",
            en: "Malay",
            fr: "malais",
            de: "Malaiisch",
            es: "malayo",
        },
        nativeName: "Bahasa Melayu",
        iso2: "MS",
        iso3: "MAY",
        direction: "ltr",
    },
    mt: {
        name: {
            tr: "Maltaca",
            en: "Maltese",
            fr: "maltais",
            de: "Maltesisch",
            es: "maltés",
        },
        nativeName: "Malti",
        iso2: "MT",
        iso3: "MLT",
        direction: "ltr",
    },
    my: {
        name: {
            tr: "Birman dili",
            en: "Burmese",
            fr: "birman",
            de: "Birmanisch",
            es: "birmano",
        },
        nativeName: "မြန်မာဘာသာ",
        iso2: "MY",
        iso3: "BUR",
        direction: "ltr",
    },
    na: {
        name: {
            tr: "Nauru dili",
            en: "Nauru",
            fr: "nauruan",
            de: "Nauruisch",
            es: "nauruano",
        },
        nativeName: "Dorerin Naoero",
        iso2: "NA",
        iso3: "NAU",
        direction: "ltr",
    },
    nb: {
        name: {
            tr: "Norveççe Bokmål",
            en: "Norwegian Bokmål",
            fr: "norvégien bokmål",
            de: "Norwegisch",
            es: "noruego bokmal",
        },
        nativeName: "Norsk bokmål",
        iso2: "NB",
        iso3: "NOB",
        direction: "ltr",
    },
    nd: {
        name: {
            tr: "Kuzey Ndebele",
            en: "North Ndebele",
            fr: "ndébélé du Nord",
            de: "Nord-Ndebele",
            es: "ndebele septentrional",
        },
        nativeName: "IsiNdebele",
        iso2: "ND",
        iso3: "NDE",
        direction: "ltr",
    },
    ne: {
        name: {
            tr: "Nepalce",
            en: "Nepali",
            fr: "népalais",
            de: "Nepalesisch",
            es: "nepalí",
        },
        nativeName: "नेपाली",
        iso2: "NE",
        iso3: "NEP",
        direction: "ltr",
    },
    ng: {
        name: {
            tr: "Ndonga",
            en: "Ndonga",
            fr: "ndonga",
            de: "Ndonga",
            es: "ndonga",
        },
        nativeName: "Owambo",
        iso2: "NG",
        iso3: "NDO",
        direction: "ltr",
    },
    nl: {
        name: {
            tr: "Felemenkçe",
            en: "Dutch",
            fr: "Néerlandais",
            de: "Niederländisch",
            es: "Neerlandés",
        },
        nativeName: "Nederlands",
        iso2: "NL",
        iso3: "DUT",
        direction: "ltr",
    },
    nn: {
        name: {
            tr: "Norveççe Nynorsk",
            en: "Norwegian Nynorsk",
            fr: "norvégien nynorsk",
            de: "Norwegisch",
            es: "noruego nynorsk",
        },
        nativeName: "Norsk nynorsk",
        iso2: "NN",
        iso3: "NNO",
        direction: "ltr",
    },
    no: {
        name: {
            tr: "Norveççe",
            en: "Norwegian",
            fr: "Norvégien",
            de: "Norwegisch",
            es: "Noruego",
        },
        nativeName: "Norsk",
        iso2: "NO",
        iso3: "NOR",
        direction: "ltr",
    },
    nr: {
        name: {
            tr: "Güney Ndebele",
            en: "South Ndebele",
            fr: "ndébélé du Sud",
            de: "Süd-Ndebele",
            es: "ndebele meridional",
        },
        nativeName: "IsiNdebele",
        iso2: "NR",
        iso3: "NBL",
        direction: "ltr",
    },
    nv: {
        name: {
            tr: "Navaho dili",
            en: "Navajo",
            fr: "navajo",
            de: "Navajo",
            es: "navajo",
        },
        nativeName: "Diné bizaad",
        iso2: "NV",
        iso3: "NAV",
        direction: "ltr",
    },
    ny: {
        name: {
            tr: "Nyanja",
            en: "Nyanja",
            fr: "chewa",
            de: "Nyanja",
            es: "nyanja",
        },
        nativeName: "Chichewa",
        iso2: "NY",
        iso3: "NYA",
        direction: "ltr",
    },
    oc: {
        name: {
            tr: "Oksitan dili",
            en: "Occitan",
            fr: "occitan",
            de: "Okzitanisch",
            es: "occitano",
        },
        nativeName: "Occitan",
        iso2: "OC",
        iso3: "OCI",
        direction: "ltr",
    },
    oj: {
        name: {
            tr: "Ojibva dili",
            en: "Ojibwa",
            fr: "ojibwa",
            de: "Ojibwa",
            es: "ojibwa",
        },
        nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
        iso2: "OJ",
        iso3: "OJI",
        direction: "ltr",
    },
    om: {
        name: {
            tr: "Oromo dili",
            en: "Oromo",
            fr: "oromo",
            de: "Oromo",
            es: "oromo",
        },
        nativeName: "Afaan Oromoo",
        iso2: "OM",
        iso3: "ORM",
        direction: "ltr",
    },
    or: {
        name: {
            tr: "Oriya dili",
            en: "Odia",
            fr: "odia",
            de: "Oriya",
            es: "oriya",
        },
        nativeName: "ଓଡ଼ିଆ",
        iso2: "OR",
        iso3: "ORI",
        direction: "ltr",
    },
    os: {
        name: {
            tr: "Osetçe",
            en: "Ossetic",
            fr: "ossète",
            de: "Ossetisch",
            es: "osético",
        },
        nativeName: "Ирон æвзаг",
        iso2: "OS",
        iso3: "OSS",
        direction: "ltr",
    },
    pa: {
        name: {
            tr: "Pencapça",
            en: "Punjabi",
            fr: "pendjabi",
            de: "Punjabi",
            es: "punyabí",
        },
        nativeName: "ਪੰਜਾਬੀ",
        iso2: "PA",
        iso3: "PAN",
        direction: "ltr",
    },
    pi: {
        name: {
            tr: "Pali",
            en: "Pali",
            fr: "pali",
            de: "Pali",
            es: "pali",
        },
        nativeName: "पालि",
        iso2: "PI",
        iso3: "PLI",
        direction: "ltr",
    },
    pl: {
        name: {
            tr: "Lehçe",
            en: "Polish",
            fr: "Polonais",
            de: "Polnisch",
            es: "Polaco",
        },
        nativeName: "Polski",
        iso2: "PL",
        iso3: "POL",
        direction: "ltr",
    },
    ps: {
        name: {
            tr: "Peştuca",
            en: "Pashto",
            fr: "pachto",
            de: "Paschtu",
            es: "pastún",
        },
        nativeName: "پښتو",
        iso2: "PS",
        iso3: "PUS",
        direction: "rtl",
    },
    pt: {
        name: {
            tr: "Portekizce",
            en: "Portuguese",
            fr: "Portugais",
            de: "Portugiesisch",
            es: "Portugués",
        },
        nativeName: "Português",
        iso2: "PT",
        iso3: "POR",
        direction: "ltr",
    },
    qu: {
        name: {
            tr: "Keçuva dili",
            en: "Quechua",
            fr: "quechua",
            de: "Quechua",
            es: "quechua",
        },
        nativeName: "Runa Simi",
        iso2: "QU",
        iso3: "QUE",
        direction: "ltr",
    },
    rm: {
        name: {
            tr: "Romanşça",
            en: "Romansh",
            fr: "romanche",
            de: "Rätoromanisch",
            es: "romanche",
        },
        nativeName: "Rumantsch",
        iso2: "RM",
        iso3: "ROH",
        direction: "ltr",
    },
    rn: {
        name: {
            tr: "Kirundi",
            en: "Rundi",
            fr: "roundi",
            de: "Rundi",
            es: "kirundi",
        },
        nativeName: "Kirundi",
        iso2: "RN",
        iso3: "RUN",
        direction: "ltr",
    },
    ro: {
        name: {
            tr: "Romence",
            en: "Romanian",
            fr: "Roumain",
            de: "Rumänisch",
            es: "Rumano",
        },
        nativeName: "Română",
        iso2: "RO",
        iso3: "RUM",
        direction: "ltr",
    },
    ru: {
        name: {
            tr: "Rusça",
            en: "Russian",
            fr: "Russe",
            de: "Russisch",
            es: "Ruso",
        },
        nativeName: "Русский",
        iso2: "RU",
        iso3: "RUS",
        direction: "ltr",
    },
    rw: {
        name: {
            tr: "Kinyarwanda",
            en: "Kinyarwanda",
            fr: "kinyarwanda",
            de: "Kinyarwanda",
            es: "kinyarwanda",
        },
        nativeName: "Kinyarwanda",
        iso2: "RW",
        iso3: "KIN",
        direction: "ltr",
    },
    sa: {
        name: {
            tr: "Sanskrit",
            en: "Sanskrit",
            fr: "sanskrit",
            de: "Sanskrit",
            es: "sánscrito",
        },
        nativeName: "संस्कृतम्",
        iso2: "SA",
        iso3: "SAN",
        direction: "ltr",
    },
    sc: {
        name: {
            tr: "Sardunya dili",
            en: "Sardinian",
            fr: "sarde",
            de: "Sardisch",
            es: "sardo",
        },
        nativeName: "Sardu",
        iso2: "SC",
        iso3: "SRD",
        direction: "ltr",
    },
    sd: {
        name: {
            tr: "Sindhi dili",
            en: "Sindhi",
            fr: "sindhi",
            de: "Sindhi",
            es: "sindi",
        },
        nativeName: "سنڌي",
        iso2: "SD",
        iso3: "SND",
        direction: "rtl",
    },
    se: {
        name: {
            tr: "Kuzey Laponcası",
            en: "Northern Sami",
            fr: "same du Nord",
            de: "Nordsamisch",
            es: "sami septentrional",
        },
        nativeName: "Davvisámegiella",
        iso2: "SE",
        iso3: "SME",
        direction: "ltr",
    },
    sg: {
        name: {
            tr: "Sango",
            en: "Sango",
            fr: "sango",
            de: "Sango",
            es: "sango",
        },
        nativeName: "Sängö",
        iso2: "SG",
        iso3: "SAG",
        direction: "ltr",
    },
    sh: {
        name: {
            tr: "Sırp-Hırvat Dili",
            en: "Serbo-Croatian",
            fr: "serbo-croate",
            de: "Serbo-Kroatisch",
            es: "serbocroata",
        },
        nativeName: "Serbo-Croatian",
        iso2: "SH",
        iso3: "HBS",
        direction: "ltr",
    },
    si: {
        name: {
            tr: "Sinhali dili",
            en: "Sinhala",
            fr: "cingalais",
            de: "Singhalesisch",
            es: "cingalés",
        },
        nativeName: "සිංහල",
        iso2: "SI",
        iso3: "SIN",
        direction: "ltr",
    },
    sk: {
        name: {
            tr: "Slovakça",
            en: "Slovak",
            fr: "Slovaque",
            de: "Slowakisch",
            es: "Eslovaco",
        },
        nativeName: "Slovenčina",
        iso2: "SK",
        iso3: "SLO",
        direction: "ltr",
    },
    sl: {
        name: {
            tr: "Slovence",
            en: "Slovenian",
            fr: "Slovène",
            de: "Slowenisch",
            es: "Esloveno",
        },
        nativeName: "Slovenščina",
        iso2: "SL",
        iso3: "SLV",
        direction: "ltr",
    },
    sm: {
        name: {
            tr: "Samoa dili",
            en: "Samoan",
            fr: "samoan",
            de: "Samoanisch",
            es: "samoano",
        },
        nativeName: "Gagana Samoa",
        iso2: "SM",
        iso3: "SMO",
        direction: "ltr",
    },
    sn: {
        name: {
            tr: "Şona dili",
            en: "Shona",
            fr: "shona",
            de: "Shona",
            es: "shona",
        },
        nativeName: "ChiShona",
        iso2: "SN",
        iso3: "SNA",
        direction: "ltr",
    },
    so: {
        name: {
            tr: "Somalice",
            en: "Somali",
            fr: "somali",
            de: "Somali",
            es: "somalí",
        },
        nativeName: "Soomaali",
        iso2: "SO",
        iso3: "SOM",
        direction: "ltr",
    },
    sq: {
        name: {
            tr: "Arnavutça",
            en: "Albanian",
            fr: "Albanais",
            de: "Albanisch",
            es: "Albanés",
        },
        nativeName: "Shqip",
        iso2: "SQ",
        iso3: "ALB",
        direction: "ltr",
    },
    sr: {
        name: {
            tr: "Sırpça",
            en: "Serbian",
            fr: "Serbe",
            de: "Serbisch",
            es: "Serbio",
        },
        nativeName: "Српски",
        iso2: "SR",
        iso3: "SRP",
        direction: "ltr",
    },
    ss: {
        name: {
            tr: "Sisvati",
            en: "Swati",
            fr: "swati",
            de: "Swazi",
            es: "suazi",
        },
        nativeName: "SiSwati",
        iso2: "SS",
        iso3: "SSW",
        direction: "ltr",
    },
    st: {
        name: {
            tr: "Güney Sotho dili",
            en: "Southern Sotho",
            fr: "sotho du Sud",
            de: "Süd-Sotho",
            es: "sotho meridional",
        },
        nativeName: "Sesotho",
        iso2: "ST",
        iso3: "SOT",
        direction: "ltr",
    },
    su: {
        name: {
            tr: "Sunda dili",
            en: "Sundanese",
            fr: "soundanais",
            de: "Sundanesisch",
            es: "sundanés",
        },
        nativeName: "Basa Sunda",
        iso2: "SU",
        iso3: "SUN",
        direction: "ltr",
    },
    sv: {
        name: {
            tr: "İsveççe",
            en: "Swedish",
            fr: "Suédois",
            de: "Schwedisch",
            es: "Sueco",
        },
        nativeName: "Svenska",
        iso2: "SV",
        iso3: "SWE",
        direction: "ltr",
    },
    sw: {
        name: {
            tr: "Svahili dili",
            en: "Swahili",
            fr: "swahili",
            de: "Suaheli",
            es: "suajili",
        },
        nativeName: "Kiswahili",
        iso2: "SW",
        iso3: "SWA",
        direction: "ltr",
    },
    ta: {
        name: {
            tr: "Tamilce",
            en: "Tamil",
            fr: "tamoul",
            de: "Tamil",
            es: "tamil",
        },
        nativeName: "தமிழ்",
        iso2: "TA",
        iso3: "TAM",
        direction: "ltr",
    },
    te: {
        name: {
            tr: "Telugu dili",
            en: "Telugu",
            fr: "télougou",
            de: "Telugu",
            es: "telugu",
        },
        nativeName: "తెలుగు",
        iso2: "TE",
        iso3: "TEL",
        direction: "ltr",
    },
    tg: {
        name: {
            tr: "Tacikçe",
            en: "Tajik",
            fr: "tadjik",
            de: "Tadschikisch",
            es: "tayiko",
        },
        nativeName: "Тоҷикӣ",
        iso2: "TG",
        iso3: "TGK",
        direction: "ltr",
    },
    th: {
        name: {
            tr: "Tayca",
            en: "Thai",
            fr: "thaï",
            de: "Thailändisch",
            es: "tailandés",
        },
        nativeName: "ไทย",
        iso2: "TH",
        iso3: "THA",
        direction: "ltr",
    },
    ti: {
        name: {
            tr: "Tigrinya dili",
            en: "Tigrinya",
            fr: "tigrigna",
            de: "Tigrinya",
            es: "tigriña",
        },
        nativeName: "ትግርኛ",
        iso2: "TI",
        iso3: "TIR",
        direction: "ltr",
    },
    tk: {
        name: {
            tr: "Türkmence",
            en: "Turkmen",
            fr: "turkmène",
            de: "Turkmenisch",
            es: "turcomano",
        },
        nativeName: "Türkmençe",
        iso2: "TK",
        iso3: "TUK",
        direction: "ltr",
    },
    tl: {
        name: {
            tr: "Tagalogca",
            en: "Tagalog",
            fr: "tagalog",
            de: "Tagalog",
            es: "tagalo",
        },
        nativeName: "Tagalog",
        iso2: "TL",
        iso3: "TGL",
        direction: "ltr",
    },
    tn: {
        name: {
            tr: "Setsvana",
            en: "Tswana",
            fr: "tswana",
            de: "Tswana",
            es: "setsuana",
        },
        nativeName: "Setswana",
        iso2: "TN",
        iso3: "TSN",
        direction: "ltr",
    },
    to: {
        name: {
            tr: "Tonga dili",
            en: "Tongan",
            fr: "tongien",
            de: "Tongaisch",
            es: "tongano",
        },
        nativeName: "Lea faka-Tonga",
        iso2: "TO",
        iso3: "TON",
        direction: "ltr",
    },
    tr: {
        name: {
            tr: "Türkçe",
            en: "Turkish",
            fr: "Turc",
            de: "Türkisch",
            es: "Turco",
        },
        nativeName: "Türkçe",
        iso2: "TR",
        iso3: "TUR",
        direction: "ltr",
    },
    ts: {
        name: {
            tr: "Tsonga",
            en: "Tsonga",
            fr: "tsonga",
            de: "Tsonga",
            es: "tsonga",
        },
        nativeName: "XiTsonga",
        iso2: "TS",
        iso3: "TSO",
        direction: "ltr",
    },
    tt: {
        name: {
            tr: "Tatarca",
            en: "Tatar",
            fr: "tatar",
            de: "Tatarisch",
            es: "tártaro",
        },
        nativeName: "Татарча",
        iso2: "TT",
        iso3: "TAT",
        direction: "ltr",
    },
    tw: {
        name: {
            tr: "Tvi",
            en: "Twi",
            fr: "twi",
            de: "Twi",
            es: "twi",
        },
        nativeName: "Twi",
        iso2: "TW",
        iso3: "TWI",
        direction: "ltr",
    },
    ty: {
        name: {
            tr: "Tahiti dili",
            en: "Tahitian",
            fr: "tahitien",
            de: "Tahitisch",
            es: "tahitiano",
        },
        nativeName: "Reo Tahiti",
        iso2: "TY",
        iso3: "TAH",
        direction: "ltr",
    },
    ug: {
        name: {
            tr: "Uygurca",
            en: "Uyghur",
            fr: "ouïghour",
            de: "Uigurisch",
            es: "uigur",
        },
        nativeName: "ئۇيغۇرچە",
        iso2: "UG",
        iso3: "UIG",
        direction: "rtl",
    },
    uk: {
        name: {
            tr: "Ukraynaca",
            en: "Ukrainian",
            fr: "Ukrainien",
            de: "Ukrainisch",
            es: "Ucraniano",
        },
        nativeName: "Українська",
        iso2: "UK",
        iso3: "UKR",
        direction: "ltr",
    },
    ur: {
        name: {
            tr: "Urduca",
            en: "Urdu",
            fr: "Ourdou",
            de: "Urdu",
            es: "Urdu",
        },
        nativeName: "اردو",
        iso2: "UR",
        iso3: "URD",
        direction: "rtl",
    },
    uz: {
        name: {
            tr: "Özbekçe",
            en: "Uzbek",
            fr: "ouzbek",
            de: "Usbekisch",
            es: "uzbeko",
        },
        nativeName: "Oʻzbekcha",
        iso2: "UZ",
        iso3: "UZB",
        direction: "ltr",
    },
    ve: {
        name: {
            tr: "Venda dili",
            en: "Venda",
            fr: "venda",
            de: "Venda",
            es: "venda",
        },
        nativeName: "Tshivenḓa",
        iso2: "VE",
        iso3: "VEN",
        direction: "ltr",
    },
    vi: {
        name: {
            tr: "Vietnamca",
            en: "Vietnamese",
            fr: "vietnamien",
            de: "Vietnamesisch",
            es: "vietnamita",
        },
        nativeName: "Tiếng Việt",
        iso2: "VI",
        iso3: "VIE",
        direction: "ltr",
    },
    vo: {
        name: {
            tr: "Volapük",
            en: "Volapük",
            fr: "volapük",
            de: "Volapük",
            es: "volapük",
        },
        nativeName: "Volapük",
        iso2: "VO",
        iso3: "VOL",
        direction: "ltr",
    },
    wa: {
        name: {
            tr: "Valonca",
            en: "Walloon",
            fr: "wallon",
            de: "Wallonisch",
            es: "valón",
        },
        nativeName: "Walon",
        iso2: "WA",
        iso3: "WLN",
        direction: "ltr",
    },
    wo: {
        name: {
            tr: "Volofça",
            en: "Wolof",
            fr: "wolof",
            de: "Wolof",
            es: "wólof",
        },
        nativeName: "Wolof",
        iso2: "WO",
        iso3: "WOL",
        direction: "ltr",
    },
    xh: {
        name: {
            tr: "Zosa dili",
            en: "Xhosa",
            fr: "xhosa",
            de: "Xhosa",
            es: "xhosa",
        },
        nativeName: "IsiXhosa",
        iso2: "XH",
        iso3: "XHO",
        direction: "ltr",
    },
    yi: {
        name: {
            tr: "Yidiş",
            en: "Yiddish",
            fr: "yiddish",
            de: "Jiddisch",
            es: "yidis",
        },
        nativeName: "ייִדיש",
        iso2: "YI",
        iso3: "YID",
        direction: "rtl",
    },
    yo: {
        name: {
            tr: "Yorubaca",
            en: "Yoruba",
            fr: "yoruba",
            de: "Yoruba",
            es: "yoruba",
        },
        nativeName: "Yorùbá",
        iso2: "YO",
        iso3: "YOR",
        direction: "ltr",
    },
    za: {
        name: {
            tr: "Zhuangca",
            en: "Zhuang",
            fr: "zhuang",
            de: "Zhuang",
            es: "zhuang",
        },
        nativeName: "Saɯ cueŋƅ",
        iso2: "ZA",
        iso3: "ZHA",
        direction: "ltr",
    },
    zh: {
        name: {
            tr: "Çince",
            en: "Chinese",
            fr: "Chinois",
            de: "Chinesisch",
            es: "Chino",
        },
        nativeName: "中文",
        iso2: "ZH",
        iso3: "CHI",
        direction: "ltr",
    },
    zu: {
        name: {
            tr: "Zuluca",
            en: "Zulu",
            fr: "zoulou",
            de: "Zulu",
            es: "zulú",
        },
        nativeName: "IsiZulu",
        iso2: "ZU",
        iso3: "ZUL",
        direction: "ltr",
    },
};

export default LANGUAGES;
