export const TEXT_LIBRARY = {
    backToHome: {
        tr: "Anasayfa'ya dön",
        en: "Back to home",
        fr: "Retour à la maison",
        de: "Zurück zur Startseite",
        es: "Volver a la página principal",
    },
    tryAgain: {
        tr: "Tekrar deneyin",
        en: "Try again",
        fr: "Réessayer",
        de: "Erneut versuchen",
        es: "Intentar de nuevo",
    },
    refreshPage: {
        tr: "Sayfayı yenile",
        en: "Refresh page",
        fr: "Actualiser la page",
        de: "Seite aktualisieren",
        es: "Actualizar la página",
    },
    copyContent: {
        tr: "İçeriği kopyala",
        en: "Copy content",
        fr: "Copier le contenu",
        de: "Inhalt kopieren",
        es: "Copiar contenido",
    },
    areYouSure: {
        tr: "Bu işlemi gerçekleştirmek istediğinize emin misiniz?",
        en: "Are you sure you want to perform this action?",
        fr: "Êtes-vous sûr de vouloir effectuer cette action?",
        de: "Sind Sie sicher, dass Sie diese Aktion ausführen möchten?",
        es: "¿Estás seguro de querer realizar esta acción?",
    },
    confirm: {
        tr: "Onayla",
        en: "Confirm",
        fr: "Confirmer",
        de: "Bestätigen",
        es: "Confirmar",
    },
    cancel: {
        tr: "Vazgeç",
        en: "Cancel",
        fr: "Annuler",
        de: "Abbrechen",
        es: "Cancelar",
    },
    searchParamsExceededMaxLength: {
        tr: "SearchParams'da maksimum uzunluk aşıldı",
        en: "Maximum length exceeded in SearchParams",
        fr: "Longueur maximale dépassée dans SearchParams",
        de: "Maximale Länge überschritten in SearchParams",
        es: "Longitud máxima excedida en SearchParams",
    },
    emptyCardMap: {
        tr: "Gösterilecek öğe bulunamadı.",
        en: "No item to display.",
        fr: "Aucun élément à afficher.",
        de: "Kein Element zum Anzeigen.",
        es: "No hay elementos para mostrar.",
    },
    loading: {
        tr: "Yükleniyor...",
        en: "Loading...",
        fr: "Chargement...",
        de: "Laden...",
        es: "Cargando...",
    },
};
